### ISSUE TITLE
Handling faulty boundary spectra from THREDDS

### ISSUE THREAD

**Issue by poplarShift** [KonstantinChri/dnora#16]
Hi, I was wondering whether you'd encountered missing/changing dimensions from one file to another. E.g. in the WAM4km spectra the longitude vector completely changes on 5 Jul from 06Z to 12Z.

The question is whether you think this is easier to handle in DNORA (by extracting coordinates file-by-file instead of once per BoundaryReader), or easier to get fixed upstream at met.no.

![image](https://user-images.githubusercontent.com/38992106/171838493-0c0298f0-37a1-4fb4-bc0e-49aa7c6b8ba2.png)

**Comment by KonstantinChri** [comment]
Hi Achim,

Thanks for informing us about this issue!

I suspect that something weird happened during the production of the file [MyWave_wam4_SPC_20180705T12Z.nc](https://thredds.met.no/thredds/catalog/fou-hi/mywavewam4archive/2018/07/05/catalog.html) since its size (196.5MB) is much smaller than usual (351.5MB). Therefore, I think we should not trust the data from files where the format (or the size) is not the standard.  

![image](https://user-images.githubusercontent.com/67804784/171879200-92a03166-9256-4098-a5d0-483aac6d78bc.png)


A possible solution is to skip/neglect these files and extract the missing data from the previous file in DNORA. I think that it is difficult to get fixed upstream at met.no due to operational issues. 

It is generally better to use the NORA3 spectrum for downscaling/hindcast simulations than the WAM4 forecast archive due to production issues (missing files) and quality.   

PS: [WW3 forecast]( https://thredds.met.no/thredds/catalog/ww3_4km_latest_files/catalog.html) now includes spectrum files with the same format as WAM4. However, we haven't incorporated these spectra in DNORA yet.

**Comment by bjorkqvi** [comment]
I think this regards to one of your pull request. I think we should simply define what a "bad file" is, and the jump over them using the previous one.

**Comment by bjorkqvi** [comment]
Just pushed a new dev-version. This now seems to work:

from dnora import bnd, grd, mdl, wnd

grid = grd.Grid(lon=(4.00, 5.73), lat=(60.53, 61.25), name='Skjerjehamn')
grid.set_spacing(dm=10000)

model = mdl.WW3(grid, start_time = '2018-07-15T18:00', end_time = '2018-07-16T12:00')
model.import_boundary(bnd.read_metno.WAM4km())

The reader patches the missing 16T00 file with the right spectra from the 15T18 file.

It should check that there is enough data in the file it is patching from, but I didn't check this yet. If the first file is missing, then we are out of luck.

An incosistent file is there treated as a missing file and skipped.
